#pragma once
#include "Layer.hpp"
#include "Dense.hpp"
#include "Conv2D.hpp"
#include "MaxPooling2D.hpp"
#include "Flatten.hpp"
#include "ResidualBlock.hpp"
#include "Activation.hpp"
#include "Upscaling.hpp"